// swift-tools-version: 5.10
// This file is auto-generated by the release script.
// WARNING: Manual edits may be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "NamiPairing",
    platforms: [
        .iOS(.v14),
    ],
    products: [
        .library(
            name: "NamiPairing",
            targets: ["NamiPairingFramework"]),
    ],
    targets: [
        .binaryTarget(
            name: "NamiPairingFramework",
            path: "Sources/NamiPairing/NamiPairingFramework.xcframework"),
    ]
)
