// swift-tools-version: 5.8
// This file is auto-generated by the release script.
// WARNING: Manual edits may be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "NamiPairing",
    platforms: [
        .iOS(.v14),
        .macOS(.v10_15),
    ],
    products: [
        // Main library with core pairing logic.
        .library(
            name: "NamiPairing",
            targets: ["NamiPairingCore"]
        ),
        // Backwards-compatible product name for "no UI" usage.
        .library(
            name: "NamiPairing-NoUI",
            targets: ["NamiPairingCore"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/airbnb/lottie-spm.git", .upToNextMajor(from: "4.4.3"))
    ],
    targets: [
        // Binary XCFramework with all core functionality.
        .binaryTarget(
            name: "NamiPairingFramework",
            path: "Sources/NamiPairing/NamiPairingFramework.xcframework"
        ),
        // Thin Swift wrapper target used by clients.
        .target(
            name: "NamiPairingCore",
            dependencies: [
                "NamiPairingFramework",
                .product(name: "Lottie", package: "lottie-spm")
            ],
            path: "Sources/NamiPairing/NamiPairingCore"
        )
    ]
)
